### ISSUE TITLE
Can't install on AWS Linux

### ISSUE THREAD

**Issue by jarrettj** [highcharts/node-export-server#113]
#### Expected behaviour
Should install node export server

#### Actual behaviour

Does not install. See error below:

```
> highcharts-export-server@2.0.7 install /usr/lib/node_modules/highcharts-export-server
> node ./build.js


/usr/lib/node_modules/highcharts-export-server/build.js:145
        let scriptOriginal = script;
            ^^^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
npm ERR! weird error 8
npm ERR! not ok code 0
```

This is on an AWS Linux AMI. 
```
uname -a
Linux ip-10-0-13-19 4.9.76-3.78.amzn1.x86_64 #1 SMP Fri Jan 12 19:51:35 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
node -v
v0.10.48
```

#### Reproduction steps
 
sudo npm install highcharts-export-server -g

**Comment by cvasseng** [comment]
Hi, you're running a very very old version of node. The minimum supported version is v6.x.

Please try upgrading node.

**Comment by jarrettj** [comment]
Hi @cvasseng :)

Thanks for the help man, it worked getting me pass that error.

New issue is weird!:
```
Phantom installation failed { Error: EACCES: permission denied, link '/tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1518436544145/phantomjs-2.1.1-linux-x86_64' -> '/usr/lib/node_modules/highcharts-export-server/node_modules/phantomjs-prebuilt/lib/phantom'
  errno: -13,
  code: 'EACCES',
  syscall: 'link',
  path: '/tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1518436544145/phantomjs-2.1.1-linux-x86_64',
  dest: '/usr/lib/node_modules/highcharts-export-server/node_modules/phantomjs-prebuilt/lib/phantom' } Error: EACCES: permission denied, link '/tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1518436544145/phantomjs-2.1.1-linux-x86_64' -> '/usr/lib/node_modules/highcharts-export-server/node_modules/phantomjs-prebuilt/lib/phantom'
```

There's no folder at location:
```
/usr/lib/node_modules/highcharts-export-server/node_modules/phantomjs-prebuilt/lib/phantom 
```

Regards.
JJ

**Comment by cvasseng** [comment]
This looks to be a permission issue. The user you're installing under does not have access to /usr/lib. 

Did you use a package manager to upgrade node/npm? What's the permissions on `/usr/lib/node_modules`?

**Comment by jarrettj** [comment]
Permissions are are root on that folder:

Added --unsafe-perm option. And that seems to have worked. Found this  https://github.com/Medium/phantomjs/issues/707

Checking if this can be scripted. Hopefully it can. Not sure what the implications would be for using --unsafe-perm.

**Comment by jarrettj** [comment]
It installs closing.
