### ISSUE TITLE
uncaughtException: TypeError: "file" argument must be a non-empty string

### ISSUE THREAD

**Issue by fsonmez** [highcharts/node-export-server#132]
I got this error when I run the command as in the readme, any ideas? 

/usr/local/bin/highcharts-export-server -infile /var/www/clients/client0/web1/web/highcharts-export-server/basic.json -outfile /var/www/clients/client0/web1/web/highcharts-export-server/outfile1.png  > /var/www/clients/client0/web1/web/highcharts-export-server/debug.log 2>&1

**uncaughtException: TypeError: "file" argument must be a non-empty string**
    at normalizeSpawnArguments (child_process.js:383:11)
    at exports.spawn (child_process.js:496:38)
    at Object.exports.exec (/usr/local/lib/node_modules/highcharts-export-server/node_modules/phantomjs-prebuilt/lib/phantomjs.js:72:10)
    at spawnWorker (/usr/local/lib/node_modules/highcharts-export-server/lib/phantompool.js:127:32)
    at Object.init [as initPool] (/usr/local/lib/node_modules/highcharts-export-server/lib/phantompool.js:329:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/highcharts-export-server/bin/cli.js:274:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)

**Comment by cvasseng** [comment]
Can you try running:

`/usr/local/bin/highcharts-export-server -infile /var/www/clients/client0/web1/web/highcharts-export-server/basic.json -outfile /var/www/clients/client0/web1/web/highcharts-export-server/outfile1.png -logLevel 4`

and post the output?

**Comment by BlaM** [comment]
Same problem here. Output with logLevel 4 does not really give any usable hints, I think...

        __  ___       __         __               __
       / / / (_)___ _/ /_  _____/ /_  ____ ______/ /______
      / /_/ / / __ `/ __ \/ ___/ __ \/ __ `/ ___/ __/ ___/
     / __  / / /_/ / / / / /__/ / / / /_/ / /  / /_(__  )
    /_/ /_/_/\__, /_/ /_/\___/_/ /_/\__,_/_/   \__/____/
            ____//___/                  __     _____
           / ____/  ______  ____  _____/ /_   / ___/___  ______   _____  _____
          / __/ | |/_/ __ \/ __ \/ ___/ __/   \__ \/ _ \/ ___/ | / / _ \/ ___/
         / /____>  </ /_/ / /_/ / /  / /_    ___/ /  __/ /   | |/ /  __/ /
        /_____/_/|_/ .___/\____/_/   \__/   /____/\___/_/    |___/\___/_/
                  /_/
                                                                      v2.0.15
    Thu Aug 09 2018 13:55:47 GMT+0200 (CEST) [verbose] attaching exit listeners to the process..
    Thu Aug 09 2018 13:55:47 GMT+0200 (CEST) [verbose] Pool started:
        maxWorkers: 1
        initialWorkers: 1
        workLimit: 60
        listening to process exit: true
    Thu Aug 09 2018 13:55:47 GMT+0200 (CEST) [verbose] phantom 1 - spawning worker
    uncaughtException: TypeError: "file" argument must be a non-empty string
        at normalizeSpawnArguments (child_process.js:383:11)
        at exports.spawn (child_process.js:496:38)
        at Object.exports.exec (/root/highcharts-server/node_modules/phantomjs-prebuilt/lib/phantomjs.js:72:10)
        at spawnWorker (/root/highcharts-server/lib/phantompool.js:127:32)
        at Object.init [as initPool] (/root/highcharts-server/lib/phantompool.js:330:9)
        at Object.<anonymous> (/root/highcharts-server/bin/cli.js:281:14)
        at Module._compile (module.js:652:30)
        at Object.Module._extensions..js (module.js:663:10)
        at Module.load (module.js:565:32)
        at tryModuleLoad (module.js:505:12)
    Thu Aug 09 2018 13:55:47 GMT+0200 (CEST) [notice] terminating, killing all running phantom processes

**Comment by aik099** [comment]
Same for me.

**Comment by neotheq** [comment]
phantomjs --version :: 2.1.1
node -v :: v8.12.0
npm -v :: 6.4.1
highcharts :: v2.0.15

Had to reinstall node (was 10.x -> downgraded to 8.x), cleared all installed packages via npm uninstall <package> -g and reinstalled the packages via this:

npm install -g phantomjs --unsafe-perm
npm install highcharts-export-server -g --unsafe-perm

I know the first steps (downgrading & clearing all packages) won't help for every situation but for me this was just fine since it's an testing env and shows that there is a way to at least somehow solves this. Maybe some of you guys get to figure out a better way, that's why attatched my versions. GL

**Comment by aik099** [comment]
If you install without "package install scripts" first and then invoke them later, then it will work.
