### ISSUE TITLE
Error: write EPIPE and 0x03 error exporting image

### ISSUE THREAD

**Issue by markathomas** [highcharts/node-export-server#166]
#### Expected behaviour

Chart is exported correctly

#### Actual behaviour
Export returns no image

Here's from the log file:
```
Sat Sep 08 2018 14:40:50 GMT+0000 (UTC) [verbose] got incoming HTTP request 9b2e15a622ab4ec39b3b9b1db2d05ad7
Sat Sep 08 2018 14:40:50 GMT+0000 (UTC) [verbose] starting export
Sat Sep 08 2018 14:40:50 GMT+0000 (UTC) [verbose] attempting to export from raw input
Sat Sep 08 2018 14:40:50 GMT+0000 (UTC) [verbose] phantom - received work, finding available worker
Sat Sep 08 2018 14:40:50 GMT+0000 (UTC) [verbose] phantom - found available worker
Sat Sep 08 2018 14:40:50 GMT+0000 (UTC) [verbose] phantom 2 - starting work
Sat Sep 08 2018 14:40:55 GMT+0000 (UTC) [error] socket error: { Error: write EPIPE
    at _errnoException (util.js:992:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:864:14) code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }
Sat Sep 08 2018 14:40:56 GMT+0000 (UTC) [error] socket error: { Error: write EPIPE
    at _errnoException (util.js:992:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:864:14) code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }
Sat Sep 08 2018 14:40:57 GMT+0000 (UTC) [notice] phantom worker 2 finished work 9b2e15a622ab4ec39b3b9b1db2d05ad7 in 6703 ms
Sat Sep 08 2018 14:41:17 GMT+0000 (UTC) [verbose] got incoming HTTP request cdf617b7697f4437beda6160a315ed3c
Sat Sep 08 2018 14:41:17 GMT+0000 (UTC) [verbose] starting export
Sat Sep 08 2018 14:41:17 GMT+0000 (UTC) [verbose] attempting to export from raw input
Sat Sep 08 2018 14:41:17 GMT+0000 (UTC) [verbose] phantom - received work, finding available worker
Sat Sep 08 2018 14:41:17 GMT+0000 (UTC) [verbose] phantom - found available worker
Sat Sep 08 2018 14:41:17 GMT+0000 (UTC) [verbose] phantom 2 - starting work
Sat Sep 08 2018 14:41:20 GMT+0000 (UTC) [notice] phantom worker 2 - process was closed
Sat Sep 08 2018 14:41:20 GMT+0000 (UTC) [error] work cdf617b7697f4437beda6160a315ed3c could not be completed, sending: 0x03 error when performing chart generation: please check your input data
```

This is after the upgrade to master branch with the Express upgrade.

**Comment by markathomas** [comment]
Here's another error that's popping up:
```
Sat Sep 08 2018 18:24:40 GMT+0000 (UTC) [error] phantom 5 - error starting work { Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:364:12)
    at Object.worker.work (/node-export-server/lib/phantompool.js:264:34)
    at Object.postWork (/node-export-server/lib/phantompool.js:360:13)
    at exec (/node-export-server/lib/chart.js:145:15)
    at doExport (/node-export-server/lib/chart.js:189:9)
    at module.exports (/node-export-server/lib/chart.js:305:20)
    at handlePost (/node-export-server/lib/server.js:204:5)
    at Layer.handle [as handle_request] (/node-export-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/node-export-server/node_modules/express/lib/router/route.js:137:13)
```

**Comment by AntonAI** [comment]
Any news on this? I'm getting a very similar error, but with `0x04` code when running as a Node.js module:

```
Wed Oct 03 2018 16:55:43 GMT-0700 (PDT) [verbose] starting export
Wed Oct 03 2018 16:55:43 GMT-0700 (PDT) [verbose] attempting to export from raw input
Wed Oct 03 2018 16:55:43 GMT-0700 (PDT) [verbose] phantom - received work, finding available worker
error: report-Q14X41538610608284: Error generating chart: 0x04 error when performing chart generation: please check your input data
Wed Oct 03 2018 16:55:43 GMT-0700 (PDT) [notice] restarting worker. working = false
error: uncaughtException: write EPIPE date=Wed Oct 03 2018 16:55:43 GMT-0700 (PDT), pid=8607, uid=501, gid=20, cwd=/Users/netus01/Documents/Software/Sensemetrics/Reports, execPath=/usr/local/bin/node, version=v8.11.3, argv=[/usr/local/bin/node, /Users/netus01/Documents/Software/Sensemetrics/Reports/bin/www], rss=407126016, heapTotal=336502784, heapUsed=222883440, external=2077655, loadavg=[4.23681640625, 4.88623046875, 4.794921875], uptime=176057
Error: write EPIPE
    at _errnoException (util.js:992:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:864:14)
uncaughtException: { Error: write EPIPE
    at _errnoException (util.js:992:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:864:14) code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }
```

**Comment by AntonAI** [comment]
Tagging @cvasseng just in case he missed this...

**Comment by AntonAI** [comment]
@markathomas @cvasseng 
After further examination, I don't think my issue relates to this. I have outlined my problem here: https://github.com/highcharts/node-export-server/issues/171

**Comment by PaulDalek** [comment]
Closing issue due to inactivity.
