### ISSUE TITLE
export server very low

### ISSUE THREAD

**Issue by MOUMBE** [highcharts/node-export-server#21]
Hello,
Export server not working when i start server with forever.

module.js:471
    throw err;
    ^

Error: Cannot find module 'colors'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ubuntu/highcharts/node-export-server/lib/index.js:28:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
error: Forever detected script exited with code: 1

I solve this first issue by creating repo node_module and copy all module needed.
After that, server start, but it very slow when query server

Thanks

**Comment by cvasseng** [comment]
Hi, did you run `npm install` before attempting to start it with forever?

PhantomJS can be fairly hungry when it comes to memory and CPU, so the performance will vary greatly based on the hardware you're running it on, the complexity of the charts, the number of simultaneous requests, and the IO capacity of the server. I highly recommend running it with at least 1GB of memory, and two CPU cores or more if you expect medium/heavy traffic.

**Comment by larsac07** [comment]
Closing this for now, as there was no response from O.P. for several months.
