### ISSUE TITLE
highcharts-export-server command failing with certain nodejs and npm versions

### ISSUE THREAD

**Issue by devDudeGS** [highcharts/node-export-server#232]
#### Expected behaviour
Running `highcharts-export-server` should start the server.

#### Actual behaviour
The command (with and without options) throws "SyntaxError: Unexpected token ..."
![highcharts-export-server](https://user-images.githubusercontent.com/26152295/73953526-8a5c7780-48ce-11ea-9ad2-a24205addc65.PNG)

#### Reproduction steps
NOTE: In our scenario, these versions are determined and installed via Docker using epel-release-latest-7.
1. Install nodejs-6.17.1
2. Install npm-3.10.10
3. Install highcharts-export-server with `npm install highcharts-export-server -g`
4. Run with `highcharts-export-server`

On systems with other nodejs and npm versions, this error does not appear.

**Comment by pawelfus** [comment]
Thanks for reporting. It seems that one of dependencies is using spread on an object, which is not supported in old version of node (support added in v8.6.0).

AFAIK node v6 is no longer supported, the oldest one is node v10 (v8 has reached LTS limit recently). I strongly recommend to use at least node v10.

Note: Most probably we should change node's engine in package.json to v8.6.0, because mdirp works since v8. @cvasseng - what do you think?

**Comment by devDudeGS** [comment]
@pawelfus Thanks for your response!

I can discuss increasing the node version with my team, but in the meantime I found a workaround related to mkdirp.

[This module](https://www.npmjs.com/package/mkdirp) was updated 13 days ago from [this GitHub repo](https://github.com/substack/node-mkdirp) to [this one with the opts-arg.js file](https://github.com/isaacs/node-mkdirp/blob/master/lib/opts-arg.js). Highcharts Node.js export server uses the latest mkdirp version as a dependency in its package.json file. But by removing the mkdirp dependency files and in package.json, I can install the older version (0.5.1) globally and that solves our problem.

**Comment by pawelfus** [comment]
Yes, you are right! Thanks for pointing this out.

Related ticket #233

**Comment by devDudeGS** [comment]
As an update, I had to do this with another package: [uuid](https://www.npmjs.com/package/uuid), which recently updated to 7.0.1 (released 2/25/20). By rolling it back to 3.4.0 in the same way as mkdirp above, I was once again able to bypass the issue with running highcharts-export-server.

**Comment by FEAprince** [comment]
While create a build getting this error, any have idea about how to solve this error? 

#0 27.93 [commonjs--resolver] Unexpected token (44:209) in /app/node_modules/highcharts/highcharts.js
#0 27.93 file: /app/node_modules/highcharts/highcharts.js:44:209
#0 27.93 42: b)&&(w[b]="day")})}c.info=B(d,{higherRanks:w,totalRange:n*b});return c};p.prototype.getDateFormat=function(d,e,k,p){var m=this.dateFormat("%m-%d %H:%M:%S.%L",e),c={millisecond:15,second:12,minute:9,hour:6,day:3},w="millisecond";for(f in h){if(d===h.week&&+this.dateFormat("%w",e)===k&&"00:00:00.000"===m.substr(6)){var f="week";break}if(h[f]>d){f=w;break}if(c[f]&&m.substr(c[f])!=="01-01 00:00:00.000".substr(c[f]))break;"week"!==f&&(w=f)}return this.resolveDTLFormat(p[f]).main};return p}();"";return g});
#0 27.93 43: K(g,"Core/Defaults.js",[g["Core/Chart/ChartDefaults.js"],g["Core/Color/Color.js"],g["Core/Globals.js"],g["Core/Color/Palettes.js"],g["Core/Time.js"],g["Core/Utilities.js"]],function(a,g,x,F,C,B){g=g.parse;var A=B.merge,t={colors:F.colors,symbols:["circle","diamond","square","triangle","triangle-down"],lang:{loading:"Loading...",months:"January February March April May June July August September October November December".split(" "),shortMonths:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),
#0 27.93 44: weekdays:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),decimalPoint:".",numericSymbols:"kMGTPE".split(""),resetZoom:"Reset zoom",resetZoomTitle:"Reset zoom level 1:1",thousandsSep:" "},global:{},time:{Date:void 0,getTimezoneOffset:void 0,timezone:void 0,timezoneOffset:0,useUTC:!0},chart:a,title:{text:"Chart title",align:"center",margin:15,widthAdjust:-44},subtitle:{text:"",align:"center",widthAdjust:-44},caption:{margin:15,text:"",align:"left",verticalAlign:"bottom"},plotOptions:{},
#0 27.93                                                                                                                  
                                                                                                    ^
#0 27.93 45: labels:{style:{position:"absolute",color:"#333333"}},legend:{enabled:!0,align:"center",alignColumns:!0,className:"highcharts-no-tooltip",layout:"horizontal",labelFormatter:function(){return this.name},borderColor:"#999999",borderRadius:0,navigation:{activeColor:"#003399",inactiveColor:"#cccccc"},itemStyle:{color:"#333333",cursor:"pointer",fontSize:"12px",fontWeight:"bold",textOverflow:"ellipsis"},itemHoverStyle:{color:"#000000"},itemHiddenStyle:{color:"#cccccc"},shadow:!1,itemCheckboxStyle:{position:"absolute",
#0 27.93 46: width:"13px",height:"13px"},squareSymbol:!0,symbolPadding:5,verticalAlign:"bottom",x:0,y:0,title:{style:{fontWeight:"bold"}}},loading:{labelStyle:{fontWeight:"bold",position:"relative",top:"45%"},style:{position:"absolute",backgroundColor:"#ffffff",opacity:.5,textAlign:"center"}},tooltip:{enabled:!0,animation:x.svg,borderRadius:3,dateTimeLabelFormats:{millisecond:"%A, %b %e, %H:%M:%S.%L",second:"%A, %b %e, %H:%M:%S",minute:"%A, %b %e, %H:%M",hour:"%A, %b %e, %H:%M",day:"%A, %b %e, %Y",week:"Week from %A, %b %e, %Y",
#0 27.94 error during build:
#0 27.94 SyntaxError: Unexpected token (44:209) in /app/node_modules/highcharts/highcharts.js
#0 27.94     at Parser.pp$4.raise (file:///app/node_modules/rollup/dist/es/shared/rollup.js:19420:13)
#0 27.94     at Parser.pp$9.unexpected (file:///app/node_modules/rollup/dist/es/shared/rollup.js:16714:8)
#0 27.94     at Parser.pp$5.parseIdent (file:///app/node_modules/rollup/dist/es/shared/rollup.js:19351:10)
#0 27.94     at Parser.pp$5.parsePropertyName (file:///app/node_modules/rollup/dist/es/shared/rollup.js:19155:109)        
#0 27.94     at Parser.pp$5.parseProperty (file:///app/node_modules/rollup/dist/es/shared/rollup.js:19082:8)
#0 27.94     at Parser.pp$5.parseObj (file:///app/node_modules/rollup/dist/es/shared/rollup.js:19036:21)
#0 27.94     at Parser.pp$5.parseExprAtom (file:///app/node_modules/rollup/dist/es/shared/rollup.js:18771:17)
#0 27.94     at Parser.pp$5.parseExprSubscripts (file:///app/node_modules/rollup/dist/es/shared/rollup.js:18587:19)       
#0 27.94     at Parser.pp$5.parseMaybeUnary (file:///app/node_modules/rollup/dist/es/shared/rollup.js:18553:17)
#0 27.94     at Parser.pp$5.parseExprOps (file:///app/node_modules/rollup/dist/es/shared/rollup.js:18480:19)
#0 27.94     at Parser.pp$5.parseMaybeConditional (file:///app/node_modules/rollup/dist/es/shared/rollup.js:18463:19)     
#0 27.94     at Parser.pp$5.parseMaybeAssign (file:///app/node_modules/rollup/dist/es/shared/rollup.js:18430:19)
#0 27.94     at Parser.pp$8.parseVar (file:///app/node_modules/rollup/dist/es/shared/rollup.js:17257:24)
#0 27.94     at Parser.pp$8.parseVarStatement (file:///app/node_modules/rollup/dist/es/shared/rollup.js:17121:8)
#0 27.94     at Parser.pp$8.parseStatement (file:///app/node_modules/rollup/dist/es/shared/rollup.js:16869:17)
#0 27.94     at Parser.pp$8.parseBlock (file:///app/node_modules/rollup/dist/es/shared/rollup.js:17190:21)
#0 27.94     at Parser.pp$5.parseFunctionBody (file:///app/node_modules/rollup/dist/es/shared/rollup.js:19246:22)
#0 27.94     at Parser.pp$8.parseFunction (file:///app/node_modules/rollup/dist/es/shared/rollup.js:17312:8)
#0 27.94     at Parser.pp$5.parseExprAtom (file:///app/node_modules/rollup/dist/es/shared/rollup.js:18776:17)
#0 27.94     at Parser.pp$5.parseExprSubscripts (file:///app/node_modules/rollup/dist/es/shared/rollup.js:18587:19)       
#0 27.94     at Parser.pp$5.parseMaybeUnary (file:///app/node_modules/rollup/dist/es/shared/rollup.js:18553:17)
#0 27.94     at Parser.pp$5.parseExprOps (file:///app/node_modules/rollup/dist/es/shared/rollup.js:18480:19)
#0 27.94     at Parser.pp$5.parseMaybeConditional (file:///app/node_modules/rollup/dist/es/shared/rollup.js:18463:19)     
#0 27.94     at Parser.pp$5.parseMaybeAssign (file:///app/node_modules/rollup/dist/es/shared/rollup.js:18430:19)
#0 27.94     at Parser.pp$5.parseExprList (file:///app/node_modules/rollup/dist/es/shared/rollup.js:19299:18)
#0 27.94     at Parser.pp$5.parseSubscript (file:///app/node_modules/rollup/dist/es/shared/rollup.js:18649:25)
#0 27.94     at Parser.pp$5.parseSubscripts (file:///app/node_modules/rollup/dist/es/shared/rollup.js:18606:24)
#0 27.94     at Parser.pp$5.parseExprSubscripts (file:///app/node_modules/rollup/dist/es/shared/rollup.js:18590:21)       
#0 27.94     at Parser.pp$5.parseMaybeUnary (file:///app/node_modules/rollup/dist/es/shared/rollup.js:18553:17)
#0 27.94     at Parser.pp$5.parseExprOps (file:///app/node_modules/rollup/dist/es/shared/rollup.js:18480:19)
#0 27.94     at Parser.pp$5.parseMaybeConditional (file:///app/node_modules/rollup/dist/es/shared/rollup.js:18463:19)     
#0 27.94     at Parser.pp$5.parseMaybeAssign (file:///app/node_modules/rollup/dist/es/shared/rollup.js:18430:19)
#0 27.94     at Parser.pp$5.parseExpression (file:///app/node_modules/rollup/dist/es/shared/rollup.js:18393:19)
#0 27.94     at Parser.pp$8.parseStatement (file:///app/node_modules/rollup/dist/es/shared/rollup.js:16904:45)
#0 27.94     at Parser.pp$8.parseBlock (file:///app/node_modules/rollup/dist/es/shared/rollup.js:17190:21)
#0 27.94     at Parser.pp$5.parseFunctionBody (file:///app/node_modules/rollup/dist/es/shared/rollup.js:19246:22)
#0 27.94     at Parser.pp$8.parseFunction (file:///app/node_modules/rollup/dist/es/shared/rollup.js:17312:8)
#0 27.94     at Parser.pp$5.parseExprAtom (file:///app/node_modules/rollup/dist/es/shared/rollup.js:18776:17)
#0 27.94     at Parser.pp$5.parseExprSubscripts (file:///app/node_modules/rollup/dist/es/shared/rollup.js:18587:19)       
#0 27.94     at Parser.pp$5.parseMaybeUnary (file:///app/node_modules/rollup/dist/es/shared/rollup.js:18553:17)
#0 27.94     at Parser.pp$5.parseExprOps (file:///app/node_modules/rollup/dist/es/shared/rollup.js:18480:19)
#0 27.94     at Parser.pp$5.parseMaybeConditional (file:///app/node_modules/rollup/dist/es/shared/rollup.js:18463:19)     
#0 27.94     at Parser.pp$5.parseMaybeAssign (file:///app/node_modules/rollup/dist/es/shared/rollup.js:18430:19)
#0 27.94     at Parser.pp$5.parseExprList (file:///app/node_modules/rollup/dist/es/shared/rollup.js:19299:18)
#0 27.94     at Parser.pp$5.parseSubscript (file:///app/node_modules/rollup/dist/es/shared/rollup.js:18649:25)
#0 27.94     at Parser.pp$5.parseSubscripts (file:///app/node_modules/rollup/dist/es/shared/rollup.js:18606:24)
#0 27.94     at Parser.pp$5.parseExprSubscripts (file:///app/node_modules/rollup/dist/es/shared/rollup.js:18590:21)       
#0 27.94     at Parser.pp$5.parseMaybeUnary (file:///app/node_modules/rollup/dist/es/shared/rollup.js:18553:17)
#0 27.94     at Parser.pp$5.parseExprOps (file:///app/node_modules/rollup/dist/es/shared/rollup.js:18480:19)
#0 27.94     at Parser.pp$5.parseMaybeConditional (file:///app/node_modules/rollup/dist/es/shared/rollup.js:18463:19

**Comment by jakubSzuminski** [comment]
Closing due to inactivity. 

I encourage you to take a look at our latest puppeteer version (here's a short setup guide: https://github.com/highcharts/node-export-server#puppeteer-version-information).

If this issue still persists in the newest version, feel free to report it and we will investigate it.
