### ISSUE TITLE
Please release the uuid dependency fix

### ISSUE THREAD

**Issue by hvt** [highcharts/node-export-server#242]
Hey @cvasseng, you committed the uuid dependency fix (https://github.com/highcharts/node-export-server/commit/e3bd98c8c1947782ac0bf0efbac57891fd01ef2c), but did not update the package's version in `package.json`.

Therefore, `uuid:8.0.0` gets installed, resulting in this error during startup of `highcharts-export-server`:
```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'uuid/v4'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/highcharts-export-server/lib/server.js:38:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

Could you please increment the package version :]?

**Comment by cvasseng** [comment]
Hi @hvt, package version has been bumped and the latest version published on NPM. Thanks for the nudge!
