### ISSUE TITLE
Unable to install in node 12.19.0 Docker

### ISSUE THREAD

**Issue by danielbecroft** [highcharts/node-export-server#258]
#### Expected behaviour
Running `npm install highcharts-export-server -g` inside of a Node 12.x Docker image should install the application correctly.

#### Actual behaviour

Permission errors are received during the installation process:

```
npm WARN deprecated phantomjs-prebuilt@2.1.14: this package is now deprecated
npm WARN deprecated mkdirp@0.5.0: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.79.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated har-validator@2.0.6: this library is no longer supported
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

> highcharts-export-server@2.0.28 preinstall /usr/local/lib/node_modules/highcharts-export-server
> node ./pre.build.js

Preinstall: no tasks to be done, skipping
/usr/local/bin/highcharts-export-server -> /usr/local/lib/node_modules/highcharts-export-server/bin/cli.js

> phantomjs-prebuilt@2.1.14 install /usr/local/lib/node_modules/highcharts-export-server/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Receiving...

Received 22866K total.
Extracting tar contents (via spawned process)
Removing /usr/local/lib/node_modules/highcharts-export-server/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1603262445665/phantomjs-2.1.1-linux-x86_64 -> /usr/local/lib/node_modules/highcharts-export-server/node_modules/phantomjs-prebuilt/lib/phantom
Phantom installation failed [Error: EACCES: permission denied, link '/tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1603262445665/phantomjs-2.1.1-linux-x86_64' -> '/usr/local/lib/node_modules/highcharts-export-server/node_modules/phantomjs-prebuilt/lib/phantom'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'link',
  path: '/tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1603262445665/phantomjs-2.1.1-linux-x86_64',
  dest: '/usr/local/lib/node_modules/highcharts-export-server/node_modules/phantomjs-prebuilt/lib/phantom'
} Error: EACCES: permission denied, link '/tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1603262445665/phantomjs-2.1.1-linux-x86_64' -> '/usr/local/lib/node_modules/highcharts-export-server/node_modules/phantomjs-prebuilt/lib/phantom'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.14 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.14 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-21T06_40_57_794Z-debug.log
```

If I open a shell to the same base container, and attempt to install, the following is in the referenced `-debug.log` file:

```
6350 verbose lifecycle phantomjs-prebuilt@2.1.14~install: unsafe-perm in lifecycle false
6351 verbose lifecycle phantomjs-prebuilt@2.1.14~install: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/local/lib/node_modules/highcharts-export-server/node_modules/phantomjs-prebuilt/node_modules/.bin:/usr/local/lib/node_modules/highcharts-export-server/node_modules/.bin:/usr/local/lib/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
6352 verbose lifecycle phantomjs-prebuilt@2.1.14~install: CWD: /usr/local/lib/node_modules/highcharts-export-server/node_modules/phantomjs-prebuilt
6353 silly lifecycle phantomjs-prebuilt@2.1.14~install: Args: [ '-c', 'node install.js' ]
6354 silly lifecycle phantomjs-prebuilt@2.1.14~install: Returned: code: 1  signal: null
6355 info lifecycle phantomjs-prebuilt@2.1.14~install: Failed to exec install script
6356 timing action:install Completed in 16702ms
6357 verbose unlock done using /root/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
6358 timing stage:rollbackFailedOptional Completed in 907ms
6359 timing stage:runTopLevelLifecycles Completed in 47367ms
6360 verbose stack Error: phantomjs-prebuilt@2.1.14 install: `node install.js`
6360 verbose stack Exit status 1
6360 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
6360 verbose stack     at EventEmitter.emit (events.js:314:20)
6360 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
6360 verbose stack     at ChildProcess.emit (events.js:314:20)
6360 verbose stack     at maybeClose (internal/child_process.js:1021:16)
6360 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
6361 verbose pkgid phantomjs-prebuilt@2.1.14
6362 verbose cwd /
6363 verbose Linux 4.19.128-microsoft-standard
6364 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "highcharts-export-server"
6365 verbose node v12.19.0
6366 verbose npm  v6.14.8
6367 error code ELIFECYCLE
6368 error errno 1
6369 error phantomjs-prebuilt@2.1.14 install: `node install.js`
6369 error Exit status 1
6370 error Failed at the phantomjs-prebuilt@2.1.14 install script.
6370 error This is probably not a problem with npm. There is likely additional logging output above.
6371 verbose exit [ 1, true ]
```

#### Reproduction steps
The Dockerfile:
```
FROM node:12.19.0-stretch

ENV ACCEPT_HIGHCHARTS_LICENSE="YES"
RUN npm install -g highcharts-export-server
```

Then:
```
docker build -t highcharts-local .
```

#### Comments
I don't know what to do here. The PhantomJS project looks to be abandoned/suspended, but surely I'm not the only one having issues installing this package in Docker.

Are there additional steps required to get the package installed in Docker? Do I need to change users, or add pathing somewhere?

**Comment by danielbecroft** [comment]
NOTE: The same error does not occur when installing locally (ie `npm install` rather than `npm install -g`).

**Comment by danielbecroft** [comment]
I managed to resolve this myself. The problem was due to insufficient permissions, and using the solutions from here, I changed my `npm install` command to:

`npm install -g highcharts-export-server --unsafe-perm`

PhantomJS install now succeeds, and highcharts works correctly inside of docker.
