### ISSUE TITLE
Initial Export Server Config

### ISSUE THREAD

**Issue by dfeagin** [highcharts/node-export-server#261]
I am going to post some general questions here about getting my highcharts export server up and running in our environment. Highcharts support sent me here to download it and get it installed.

I have downloaded it on my Windows server that is running IIS where my web application is currently hosted that has the charts that we are having the 413 error with.

So now after downloading and installing the export server how can I verify that it is always running on say port 8080 since my IIS instance is running on port 80?

I attempted to run this command line:
highcharts-export-server --host iews001 --port 8080 --enableServer 1

but it reports the following error:
uncaughtException: TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received null
    at validateString (internal/validators.js:124:11)
    at normalizeSpawnArguments (child_process.js:411:3)
    at spawn (child_process.js:551:13)
    at Object.exports.exec (C:\Users\IE-lindev\AppData\Roaming\npm\node_modules\highcharts-export-server\node_modules\phantomjs-prebuilt\lib\phantomjs.js:72:10)
    at spawnWorker (C:\Users\IE-lindev\AppData\Roaming\npm\node_modules\highcharts-export-server\lib\phantompool.js:127:32)
    at Object.init [as initPool] (C:\Users\IE-lindev\AppData\Roaming\npm\node_modules\highcharts-export-server\lib\phantompool.js:330:9)
    at Object.<anonymous> (C:\Users\IE-lindev\AppData\Roaming\npm\node_modules\highcharts-export-server\bin\cli.js:193:10)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by dfeagin** [comment]
Figured out my issue. I was installing on a server that had calls being blocked to the internet during the installation. Once I got all of the files correctly installed the server fired right up.
