### ISSUE TITLE
Puppeteer version - exporting charts with code execution

### ISSUE THREAD

**Issue by daum** [highcharts/node-export-server#346]
We're trying to use the latest enhancements/puppeteer branch as we need to support exports which have chart configs that have custom javascript (ie data label formatters).  So for example:
```js
{
    chart: {
        type: 'column'
    },
    title: {
        text: 'Monthly Average Rainfall'
    },

    xAxis: {
        categories: [
            'Jan',
            'Feb',
        ],
    },
    series: [{
        name: 'Tokyo',
        data: [49.9, 71.5],
 				dataLabels: {
          enabled: true,
          formatter: function () {
            return Highcharts.numberFormat(this.y, 0, '.', ',');
          }
        }
    }]
}
```

Taking this as an input file and then outputting it as a PNG.  So doing this I then get this error:
```
$ node node_modules/highcharts-export-server/bin/cli.js --infile test.json --outfile test.png
    __  ___       __         __               __                          
   / / / (_)___ _/ /_  _____/ /_  ____ ______/ /______                    
  / /_/ / / __ `/ __ \/ ___/ __ \/ __ `/ ___/ __/ ___/                    
 / __  / / /_/ / / / / /__/ / / / /_/ / /  / /_(__  )                     
/_/ /_/_/\__, /_/ /_/\___/_/ /_/\__,_/_/   \__/____/                      
        ____//___/                  __     _____                          
       / ____/  ______  ____  _____/ /_   / ___/___  ______   _____  _____
      / __/ | |/_/ __ \/ __ \/ ___/ __/   \__ \/ _ \/ ___/ | / / _ \/ ___/
     / /____>  </ /_/ / /_/ / /  / /_    ___/ /  __/ /   | |/ /  __/ /    
    /_____/_/|_/ .___/\____/_/   \__/   /____/\___/_/    |___/\___/_/     
              /_/                                                         
                                                                     v3.0.0
Wed May 25 2022 17:07:10 GMT-0400 (Eastern Daylight Time) [notice] [cli] - No resources found.
Wed May 25 2022 17:07:10 GMT-0400 (Eastern Daylight Time) [notice] [cache] - Dependency cache is up to date, proceeding.
Wed May 25 2022 17:07:10 GMT-0400 (Eastern Daylight Time) [notice] [pool] - Initializing pool: min 1 max 1
Wed May 25 2022 17:07:10 GMT-0400 (Eastern Daylight Time) [verbose] [pool] - Creating pool entry f0d9d80b-30c1-4131-8cb2-afe356e070b6
Wed May 25 2022 17:07:10 GMT-0400 (Eastern Daylight Time) [verbose] [chart] - Starting exporting process.
Wed May 25 2022 17:07:10 GMT-0400 (Eastern Daylight Time) [verbose] [chart] - Attempting to export from an input file.
/home/daum/work/highcharts-example/node_modules/highcharts-export-server/lib/chart.js:194
    return doExport(options, false, endCallback);
                                    ^

ReferenceError: endCallback is not defined
    at doStraightInject (/home/daum/work/highcharts-example/node_modules/highcharts-export-server/lib/chart.js:194:37)
    at exportAsString (/home/daum/work/highcharts-example/node_modules/highcharts-export-server/lib/chart.js:266:14)
    at /home/daum/work/highcharts-example/node_modules/highcharts-export-server/lib/chart.js:313:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
```

I tried to debug it some by defining the endCallback by manipulating the code but then got errors with the width not defined.  I know this branch doesn't have full feature parity yet, so before going too far wanted to see if this type of setup is supported yet?  If not, do you have an ETA for the beta support on it?

We're running up to the current export server not working on newer installs to due a phantomjs + openssl issue.

Thanks!

**Comment by jarrettj** [comment]
Same here :( This is only because the default install has gone bust. Such sad.
