### ISSUE TITLE
Conversion fails

### ISSUE THREAD

**Issue by jarrettj** [highcharts/node-export-server#389]
Hi,

Good day.

Import server has stopped working. Tried it on various environments to confirm. 

#### Expected behaviour
Generate an image as it has done before. The simple sample I am using is:
```
{
  "title": {
    "text": "From JSON infile"
  },
  "xAxis": {
    "categories": ["Jan", "Feb", "Mar", "Apr"]
  },
  "series": [{
    "type": "column",
    "data": [5, 6, 7, 8]
  }, {
    "type": "line",
    "data": [1, 2, 3, 4]
  }]
}
```

#### Actual behaviour

Get the following error:
```
uncaughtException: TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received type object
    at validateString (internal/validators.js:125:11)
    at normalizeSpawnArguments (child_process.js:411:3)
    at spawn (child_process.js:545:16)
    at Object.exports.exec (/usr/lib/node_modules/highcharts-export-server/node_modules/phantomjs-prebuilt/lib/phantomjs.js:72:10)
    at spawnWorker (/usr/lib/node_modules/highcharts-export-server/lib/phantompool.js:127:32)
    at Object.init [as initPool] (/usr/lib/node_modules/highcharts-export-server/lib/phantompool.js:330:9)
    at Object.<anonymous> (/usr/lib/node_modules/highcharts-export-server/bin/cli.js:358:10)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
```

#### Reproduction steps
Install highcharts, on CentOS, MacOS and even Ubuntu. Using the following:
`npm install highcharts-export-server -g --unsafe-perm --ignore-scripts`

Try to convert using the following:
`highcharts-export-server -infile test.json -outfile test.png -allowCodeExecution true`

Even tried variations:
`highcharts-export-server --infile "test.json" --outfile "test.png" -allowCodeExecution true`

Node
`
root@0223a58c0c10:/var/www/html# node -v
v16.18.1
`

Even checked my previous issue where I had to lock the version to 9.2.2 https://github.com/highcharts/node-export-server/issues/314. Does not work. Any help would be much appreciated. Thanks.

Regards,
Jarrett

**Comment by PaulDalek** [comment]
Hi @jarrettj

Sorry for my slow response. I’ve checked the options provided by you and the generating chart by using the command from above works correctly. From what I can see the error refers to some of your internal validators, so it looks like it is related to some incorrect type of a file property but I cannot see that it is used in the provided example. Could you provide us with a minimal setup where this can be recreated along with versions of the export server and Highcharts you use?

**Comment by jakubSzuminski** [comment]
This does not seem to be a bug. Closing due to no response.
