### ISSUE TITLE
[ERR_REQUIRE_ESM]: require() of ES Module is not supported

### ISSUE THREAD

**Issue by m-cisse-easy-live** [highcharts/node-export-server#431]
Hello I would like to report a bug concerning the Puppeter version highcharts-export-server. I followed the GitHub documentation to install highcharts-export-server and when I wanted to use highcharts-export-server as a NodeJS module then an error was generated telling me that highcharts-export-server was not supported. Here's the server.js script I used, inspired by the documentation : 
```
// Import the Export Server module
const exporter = require('highcharts-export-server');

(async() => {
// Initialize export settings with your chart's config
// Export settings correspond to the available CLI arguments described above.
const exportSettings = {
    export: {
      type: 'png',
      options: {
        title: {
          text: 'My Chart'
        },
        xAxis: {
          categories: ["Jan", "Feb", "Mar", "Apr"]
        },
        series: [
          {
            type: 'line',
            data: [1, 3, 2, 4]
          },
          {
            type: 'line',
            data: [5, 3, 4, 2]
          }
        ]
      }
    }
  };
  
  // Initialize a pool of workers
  await exporter.initPool();
  
  // Perform an export
  exporter.startExport(exportSettings, function (res, err) {
    // The export result is now in res.
    // It will be base64 encoded (res.data).
  
    // Kill the pool when we're done with it.
    exporter.killPool();
  });
})()
```

#### Expected behaviour
The expected behavior was that it generated a chart in png format that followed the configuration I specified in a server.js script

#### Actual behaviour
`const exporter = require('highcharts-export-server');
                 ^

Error [ERR_REQUIRE_ESM]: require() of ES Module C:\XXX\XXX\node_modules\highcharts-export-server\lib\index.js from C:\Bitbucket\highchart\server.js not supported.
Instead change the require of index.js in C:\XXX\XXX\server.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (C:\XXX\XXX\server.js:2:18) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.17.1`

#### Reproduction steps
**Config :**
Windows 10
NodeJS 18.17.1
NPM 9.6.7

**Command**
`npm i highcharts-export-server@3.0.0-rc.2`
`node server.js`

**Comment by m-cisse-easy-live** [comment]
Thank you for your reply.

I cloned the repository on the `enhancement/puppeteer` branch with the command `git clone --branch enhancement/puppeteer https://github.com/highcharts/node-export-server`.
I followed the commands below : 
```
npm install
npm link
```

And ran my server.js script again and got the following error:
```
node server.js 
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module 'highcharts-export-server'
Require stack:
- C:\XXX\XXX\server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (C:\Bitbucket\highchart\server.js:2:18)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\XXX\\XXX\\server.js' ]
}

Node.js v18.17.1
```
