### ISSUE TITLE
Exporting a scatter with >6k markers fails

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/node-export-server#490]
#### Behaviour
`POST https://export.highcharts.com/ 500 (Internal Server Error)`
```
MulterError: Field value too long
    at abortWithCode (/var/app/current/node_modules/multer/lib/make-middleware.js:71:22)
    at Multipart.<anonymous> (/var/app/current/node_modules/multer/lib/make-middleware.js:78:34)
    at Multipart.emit (node:events:517:28)
    at SBMH.ssCb [as _cb] (/var/app/current/node_modules/busboy/lib/types/multipart.js:537:16)
    at feed (/var/app/current/node_modules/streamsearch/lib/sbmh.js:219:14)
    at SBMH.push (/var/app/current/node_modules/streamsearch/lib/sbmh.js:104:16)
    at Multipart._write (/var/app/current/node_modules/busboy/lib/types/multipart.js:567:19)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
```

#### Reproduction steps
https://jsfiddle.net/BlackLabel/r9mou6ka/
1. try exporting the chart to get the error

**Comment by jszuminski** [comment]
This will likely get solved with 4.0.0 after multer fieldSize has been increased by @PaulDalek in this pull request: https://github.com/highcharts/node-export-server/pull/482

**Comment by ROCarrera** [comment]
Hi! Is this released? I still have the error. Thank you very much for your support!

**Comment by jszuminski** [comment]
It's not yet released. We're planning to release this week.
