### ISSUE TITLE
Preview and download are not generating in windows

### ISSUE THREAD

**Issue by ParthasaradhiWinfo** [highcharts/node-export-server#535]
Please check the below error when starting the high charts server 
Server has been started with below error but graphs are not generated

To load grahp as image

#### Actual behaviour
    at async open (f/AppData/Roaming/npm/node_modules/highcharts-export-server/lib/browser.js:162:11)
Fri Jun 07 2024 11:37:46 GMT+0530 [notice] - [browser] attempting to get a browser instance (try 23)
Fri Jun 07 2024 11:37:46 GMT+0530 [notice] - [browser] failed: Error: Could not find Chrome (ver. 121.0.6167.85). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install chrome`) or
 2. your cache path is incorrectly configured (which is: C:\Users\\.cache\puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
    at ChromeLauncher.resolveExecutablePath (file:///C:/Users//AppData/Roaming/npm/node_modules/highcharts-export-server/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:259:27)
    at ChromeLauncher.executablePath (file:///C:/Users//AppData/Roaming/npm/node_modules/highcharts-export-server/node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:204:25)
    at ChromeLauncher.computeLaunchArguments (file:///C:/Users/RTP1COB/AppData/Roaming/npm/node_modules/highcharts-export-server/node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:97:37)
    at ChromeLauncher.launch (file:///C:/Users//AppData/Roaming/npm/node_modules/highcharts-export-server/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:44:39)
    at ChromeLauncher.launch (file:///C:/Users//AppData/Roaming/npm/node_modules/highcharts-export-server/node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:51:22)
    at PuppeteerNode.launch (file:///C:/Users//AppData/Roaming/npm/node_modules/highcharts-export-server/node_modules/puppeteer-core/lib/esm/puppeteer/node/PuppeteerNode.js:129:31)
    at open (file:///C:/Users//AppData/Roaming/npm/node_modules/highcharts-export-server/lib/browser.js:152:35)
    at open (file:///C:/Users//AppData/Roaming/npm/node_modules/highcharts-export-server/lib/browser.js:162:17)
    at async open (file:///C:/Users//AppData/Roaming/npm/node_modules/highcharts-export-server/lib/browser.js:162:11)
    at async open (file:///C:/Users/RTP1COB/AppData/Roaming/npm/node_modules/highcharts-export-server/lib/browser.js:162:11)
Fri Jun 07 2024 11:37:50 GMT+0530 [notice] - [browser] attempting to get a browser instance (try 24)
Fri Jun 07 2024 11:37:50 GMT+0530 [notice] - [pool] Initializing pool: min 4, max 8.
Fri Jun 07 2024 11:37:50 GMT+0530 [verbose] - [pool] Attaching exit listeners to the process.
Fri Jun 07 2024 11:37:50 GMT+0530 [error] - [pool] Error creating a new page in pool entry creation! [pool] Invalid page
Fri Jun 07 2024 11:37:50 GMT+0530 [error] - [pool] Error when creating worker of an event id 2: Error creating page
Fri Jun 07 2024 11:37:50 GMT+0530 [error] - [pool] Error creating a new page in pool entry creation! [pool] Invalid page
Fri Jun 07 2024 11:37:50 GMT+0530 [error] - [pool] Error when creating worker of an event id 3: Error creating page
Fri Jun 07 2024 11:37:51 GMT+0530 [error] - [pool] Error creating a new page in pool entry creation! [pool] Invalid page
Fri Jun 07 2024 11:37:51 GMT+0530 [error] - [pool] Error when creating worker of an event id 4: Error creating page
Fri Jun 07 2024 11:37:51 GMT+0530 [error] - [pool] Error creating a new page in pool entry creation! [pool] Invalid page
Fri Jun 07 2024 11:37:51 GMT+0530 [error] - [pool] Error when creating worker of an event id 5: Error creating page
Fri Jun 07 2024 11:37:51 GMT+0530 [error] - [pool] Error creating a new page in pool entry creation! [pool] Invalid page
Fri Jun 07 2024 11:37:51 GMT+0530 [error] - [pool] Error when creating worker of an event id 6: Error creating page
Fri Jun 07 2024 11:37:51 GMT+0530 [error] - [pool] Error creating a new page in pool entry creation! [pool] Invalid page
Fri Jun 07 2024 11:37:51 GMT+0530 [error] - [pool] Error when creating worker of an event id 7: Error creating page
Fri Jun 07 2024 11:37:51 GMT+0530 [error] - [pool] Error creating a new page in pool entry creation! [pool] Invalid page
Fri Jun 07 2024 11:37:51 GMT+0530 [error] - [pool] Error when creating worker of an event id 8: Error creating page
Fri Jun 07 2024 11:37:52 GMT+0530 [error] - [pool] Error creating a new page in pool entry creation! [pool] Invalid page
Fri Jun 07 2024 11:37:52 GMT+0530 [error] - [pool] Error when creating worker of an event id 9: Error creating page
Fri Jun 07 2024 11:37:52 GMT+0530 [error] - [pool] Error creating a new page in pool entry creation! [pool] Invalid page
Fri Jun 07 2024 11:37:52 GMT+0530 [error] - [pool] Error when creating worker of an event id 10: Error creating page
Fri Jun 07 2024 11:37:52 GMT+0530 [error] - [pool] Error creating a new page in pool entry creation! [pool] Invalid page
Fri Jun 07 2024 11:37:52 GMT+0530 [error] - [pool] Error when creating worker of an event id 11: Error creating page
Fri Jun 07 2024 11:37:52 GMT+0530 [error] - [pool] Error creating a new page in pool entry creation! [pool] Invalid page
Fri Jun 07 2024 11:37:52 GMT+0530 [error] - [pool] Error when creating worker of an event id 12: Error creating page
Fri Jun 07 2024 11:37:52 GMT+0530 [error] - [pool] Error creating a new page in pool entry creation! [pool] Invalid page
Fri Jun 07 2024 11:37:52 GMT+0530 [error] - [pool] Error when creating worker of an event id 13: Error creating page
Fri Jun 07 2024 11:37:53 GMT+0530 [error] - [pool] Error creating a new page in pool entry creation! [pool] Invalid page
Fri Jun 07 2024 11:37:53 GMT+0530 [error] - [pool] Error when creating worker of an event id 14: Error creating page
Fri Jun 07 2024 11:37:53 GMT+0530 [error] - [pool] Error creating a new page in pool entry creation! [pool] Invalid page
Fri Jun 07 2024 11:37:53 GMT+0530 [error] - [pool] Error when creating worker of an event id 15: Error creating page
Fri Jun 07 2024 11:37:53 GMT+0530 [error] - [pool] Error creating a new page in pool entry creation! [pool] Invalid page
Fri Jun 07 2024 11:37:53 GMT+0530 [error] - [pool] Error when creating worker of an event id 16: Error creating page
Fri Jun 07 2024 11:37:53 GMT+0530 [error] - [pool] Error creating a new page in pool entry creation! [pool] Invalid page
Fri Jun 07 2024 11:37:53 GMT+0530 [error] - [pool] Error when creating worker of an event id 17: Error creating page
Fri Jun 07 2024 11:37:54 GMT+0530 [error] - [pool] Error creating a new page in pool entry creation! [pool] Invalid page
Fri Jun 07 2024 11:37:54 GMT+0530 [error] - [pool] Error when creating worker of an event id 18: Error creating page
Fri Jun 07 2024 11:37:54 GMT+0530 [error] - [pool] Error creating a new page in pool entry creation! [pool] Invalid page
Fri Jun 07 2024 11:37:54 GMT+0530 [error] - [pool] Error when creating worker of an event id 19: Error creating page
Fri Jun 07 2024 11:37:54 GMT+0530 [error] - [pool] Error creating a new page in pool entry creation! [pool] Invalid page
Fri Jun 07 2024 11:37:54 GMT+0530 [error] - [pool] Error when creating worker of an event id 20: Error creating page
Fri Jun 07 2024 11:37:54 GMT+0530 [error] - [pool] Error creating a new page in pool entry creation! [pool] Invalid page
Fri Jun 07 2024 11:37:54 GMT+0530 [error] - [pool] Error when creating worker of an event id 21: Error creating page
Fri Jun 07 2024 11:37:54 GMT+0530 [error] - [pool] Error creating a new page in pool entry creation! [pool] Invalid page
Fri Jun 07 2024 11:37:54 GMT+0530 [error] - [pool] Error when creating worker of an event id 22: Error creating page
Fri Jun 07 2024 11:37:55 GMT+0530 [error] - [pool] Error creating a new page in pool entry creation! [pool] Invalid page
Fri Jun 07 2024 11:37:55 GMT+0530 [error] - [pool] Error when creating worker of an event id 23: Error creating page
Fri Jun 07 2024 11:37:55 GMT+0530 [error] - [pool] Error creating a new page in pool entry creation! [pool] Invalid page
Fri Jun 07 2024 11:37:55 GMT+0530 [error] - [pool] Error when creating worker of an event id 24: Error creating page
Fri Jun 07 2024 11:37:55 GMT+0530 [error] - [pool] Error creating a new page in pool entry creation! [pool] Invalid page
Fri Jun 07 2024 11:37:55 GMT+0530 [error] - [pool] Error when creating worker of an event id 25: Error creating page
Fri Jun 07 2024 11:37:55 GMT+0530 [error] - [pool] Error creating a new page in pool entry creation! [pool] Invalid page
Fri Jun 07 2024 11:37:55 GMT+0530 [error] - [pool] Error when creating worker of an event id 26: Error creating page
Fri Jun 07 2024 11:37:55 GMT+0530 [error] - [pool] Error when acquiring worker of an event id 1: TimeoutError

**Comment by jszuminski** [comment]
Closing due to inactivity and lack of reproduction.
