### ISSUE TITLE
Startup error:  no such file or directory, open '/usr/lib/node_modules/highcharts-export-server//msg/startup.msg

### ISSUE THREAD

**Issue by markuspalme** [highcharts/node-export-server#556]
I have installed `highcharts-export-server` 4.0.1 via `npm i highcharts-export-server -g`. Running

`highcharts-export-server -infile /tmp/vl1l4f0w.puh -outfile /tmp/d2s1f2yz.0t4 -width 600` results in this error message:

```
[error] - ENOENT: no such file or directory, open '/usr/lib/node_modules/highcharts-export-server//msg/startup.msg' 
 Error: ENOENT: no such file or directory, open '/usr/lib/node_modules/highcharts-export-server//msg/startup.msg'
    at Object.openSync (node:fs:573:18)
    at readFileSync (node:fs:452:35)
    at Object.printLogo (file:///usr/lib/node_modules/highcharts-export-server/lib/utils.js:330:5)
    at start (file:///usr/lib/node_modules/highcharts-export-server/bin/cli.js:51:12)
    at file:///usr/lib/node_modules/highcharts-export-server/bin/cli.js:111:1
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)
```

This can be reproduced both in an Ubuntu docker container and on Windows.

I don't think that it matters, but this is the content of the `-infile`:

```
{"xAxis":{"categories":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]},"series":[{"data":[8,9,5,4],"type":"line"},{"data":[5,3,4,2],"type":"line"}],"credits":{"enabled":false}}
```

Creating an empty file in the mentioned location fixes the issue.

**Comment by jszuminski** [comment]
Thanks for reporting @digitalbanana!

Solved with: https://github.com/highcharts/node-export-server/pull/557

And published as v4.0.2.

Please test it out and let me know if it works as expected now in the latest version.
