### ISSUE TITLE
Chart Export feature is giving CORS issue suddenly.

### ISSUE THREAD

**Issue by Neha44hz** [highcharts/node-export-server#602]
#### Expected behaviour
Png, jpg, pdf must download from chart export button

#### Actual behaviour
Its is giving CORS issue

**Comment by jszuminski** [comment]
@Neha44hz thanks for reporting! Could you please share the exact error message that you're getting in your request/response?

Also, are you just clicking the exporting button on your chart, via the `exporting.js` module? Or are you sending a custom JSON request?

Please share more details.

**Comment by foroozan** [comment]
Hello, we are having the same issue, we use highcharts in our website and the issue is reported is Download PNG is not working. exact error is:

Access to fetch at 'https://export.highcharts.com/' from origin '' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by sharmankita** [comment]
I am also facing the same issue. please update once resolved or if there is any workaround ?

**Comment by llabend** [comment]
Our web application is also encountering this issue. We are running Highcharts 11.4.6.

It happens when a user clicks on any of the download options in the hamburger menu of a highchart:
<img width="265" alt="Screenshot 2024-12-04 at 11 44 16 AM" src="https://github.com/user-attachments/assets/0ee5d502-49cf-412f-a6a7-5a57baee3a03">


The following errors are printed to the console locally and on higher environments:
`Access to fetch at 'https://export.highcharts.com/' from origin '' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

`POST https://export.highcharts.com/ net::ERR_FAILED 403 (Forbidden)`


        
       
        
       Uncaught (in promise) TypeError: Failed to fetch
    at index-DFJFBoW7.js:8:46109
    at Object.post (accessibility-C--XD5AD.js:3:106404)
    at ot.U [as exportChart] (accessibility-C--XD5AD.js:3:112682)
    at ot.onclick (accessibility-C--XD5AD.js:3:101042)
    at HTMLLIElement.onclick (accessibility-C--XD5AD.js:3:111325)`

**Comment by ericoc** [comment]
I am having a similar problem; or at least an extremely similar error message.

I ttempted to implement exporting from Highcharts at https://utilities.ericoc.com/ today.
However, I am trying to locally host as much as the front-end JavaScript code as possible.
I really would like to avoid having to host a Highcharts "export server" as well though?

You can see the error message that occurs when trying to export images from both of my Highcharts charts here:
- https://utilities.ericoc.com/electric/
- https://utilities.ericoc.com/water/
  - The "water" database and Django REST Framework API has _way_ less data, so loads faster for testing.

The source code for this `utilities.ericoc.com` Django web application is available here:
- https://github.com/ericoc/utilities
  - My Highcharts instances JavaScript _(currently)_ lives in the Django HTML template files, for example:
    - https://github.com/ericoc/utilities/blob/main/apps/core/templates/base.html
    - https://github.com/ericoc/utilities/blob/main/apps/water/templates/water.html

For example:
<img width="1436" alt="Screenshot 2024-12-14 at 2 49 52 PM" src="https://github.com/user-attachments/assets/cd588d86-19e0-46e1-be29-06f14997cf49" />
```

water/:1 Access to fetch at 'https://export-svg.highcharts.com/' from origin 'https://utilities.ericoc.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
exporting.js:11
POST https://export-svg.highcharts.com/ net::ERR_FAILED 403 (Forbidden)
    post	@	exporting.js:11
u	@	exporting.js:11
onclick	@	exporting.js:11
onclick	@	exporting.js:11

exporting.js:11

Uncaught (in promise) TypeError: Failed to fetch
at Object.post (exporting.js:11:7132)
at aH.u [as exportChart] (exporting.js:11:12687)
at aH.onclick (exporting.js:11:2079)
at HTMLLIElement.onclick (exporting.js:11:11418)
post	@	exporting.js:11
u	@	exporting.js:11
onclick	@	exporting.js:11
onclick	@	exporting.js:11
exporting.js:11 Fetch failed loading: POST "https://export-svg.highcharts.com/".
```

**Comment by ericoc** [comment]
Including the additional Highcharts JavaScript library file locally seems to have resolved my issue!

https://code.highcharts.com/modules/offline-exporting.js

**Comment by Vitalii-001** [comment]
> Including this additional Highcharts JavaScript library file locally seems to have resolved my issue!
> 
> https://code.highcharts.com/modules/offline-exporting.js
> 
> as can be seen on any of these pages using Highcharts, where exporting images seems to work okay now:
> 
> https://utilities.ericoc.com/electric/ https://utilities.ericoc.com/gas/ https://utilities.ericoc.com/water/
> 
> using the following locally hosted/referenced Highcharts JavaScript per:
> 
> https://github.com/ericoc/utilities/blob/b7bf0771827ecdb7dbbd08c18194cedf549c1fd3/apps/core/templates/base.html#L26-L30

Yep, this is indeed a working solution. Just tested it. Thanks!

**Comment by ericoc** [comment]
@Vitalii-001 awesome - thanks for confirmation! :) 

@llabend would you be able to confirm whether you are including the [offline-exporting.js](https://code.highcharts.com/modules/offline-exporting.js) JavaScript? If not, I would totally suggest that it might be worth giving it a shot since our error messages were so similar!

**Comment by llabend** [comment]
@ericoc Yes! Thank you for your detailed notes & solution, I really appreciate it. After testing locally, I deployed to my DEV environment to test out the changes there and **can confirm** that including the `OfflineExporting` module from Highcharts seems to have resolved the issue for our project.

For any Vue 3 users out there, I imported the module within each of our chart components:
`import OfflineExporting from 'highcharts/modules/offline-exporting';`

and then included it with the other Highcharts function calls:
`OfflineExporting(Highcharts);`

**Comment by shiddugmail** [comment]
Thank you everyone in this thread. 

Especially @ericoc Thank you so much for the inputs to add offline-exporting. 

I added following lines in our common component HIghChartComponent.js

import OfflineExporting from 'highcharts/modules/offline-exporting';
OfflineExporting(Highcharts);

And it worked nicely.

**Comment by mujtaba36** [comment]
"@shiddugmail Could you please confirm which version of Highcharts you are using? I am currently using Highcharts 11.4.0, but it is not working for me."

**Comment by shiddugmail** [comment]
> "@shiddugmail Could you please confirm which version of Highcharts you are using? I am currently using Highcharts 11.4.0, but it is not working for me."

Hi @mujtaba36 following are the versions I am using. 

    "highcharts": "^11.4.3"
    "highcharts-react-official": "^3.2.1"
    
Hope this helps.

**Comment by joseph-luketelo** [comment]
> Including this additional Highcharts JavaScript library file locally seems to have resolved my issue!
> 
> https://code.highcharts.com/modules/offline-exporting.js
> 
> as can be seen on any of these pages using Highcharts, where exporting images seems to work okay now:
> 
> https://utilities.ericoc.com/electric/ https://utilities.ericoc.com/natural_gas/ https://utilities.ericoc.com/water/
> 
> using the following locally hosted/referenced Highcharts JavaScript per:
> 
> https://github.com/ericoc/utilities/blob/b7bf0771827ecdb7dbbd08c18194cedf549c1fd3/apps/core/templates/base.html#L26-L30

This worked for me as well, thank you!
