### ISSUE TITLE
error when using --enableServer 1

### ISSUE THREAD

**Issue by Charlescad** [highcharts/node-export-server#617]
I try to run the server after having installed the package as in readme:

git clone https://github.com/highcharts/node-export-server
npm install
npm link

Then
highcharts-export-server --enableServer 1

node version: v20.10

#### Expected behaviour
The expected behaviour is: being able to run the server, as well as the curl code as in the example:

`"Content-Type: application/json" -X POST -d "{\"infile\":{\"title\": {\"text\": \"Chart\"}, \"xAxis\": {\"categories\": [\"Jan\", \"Feb\", \"Mar\"]}, \"series\": [{\"data\": [29.9, 71.5, 106.4]}]}}" 127.0.0.1:7801 -o chart.png`

#### Actual behavior:

Here is the error I get: on the cmd line frame where i try to highcharts-export-server --enableServer 1
`node-export-server/lib/resource_release.js:27:3)
    at process.<anonymous> (file:////node-export-server/lib/index.js:71:11)
    at process.emit (node:events:514:28)
    at process._fatalException (node:internal/process/execution:178:25)
    at processPromiseRejections (node:internal/process/promises:289:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)

Mon Dec 23 2024 16:42:59 GMT+0100 [error] - The unhandledRejection error.
    at get (file:////node-export-server/lib/browser.js:101:11)
    at shutdownCleanUp (file:////node-export-server/lib/resource_release.js:27:3)
    at process.<anonymous> (file:////node-export-server/lib/index.js:71:11)
    at process.emit (node:events:514:28)
    at process._fatalException (node:internal/process/execution:178:25)
    at processPromiseRejections (node:internal/process/promises:289:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)

curl results: not working since the server is bugging.

curl: (7) Failed to connect to 127.0.0.1 port 7801 after 2066 ms: Could not connect to server

#### Question
Do you know what is going on there?

**Comment by pratikahire-wtw** [comment]
I am facing the same issue!

**Comment by pratikahire-wtw** [comment]
Hi @Charlescad 

Disable your VPN if it is on and then do the npm install and server startup commands. If that does not work then forcefully install highcharts-export-server@3.0.3, it worked for me.

**Comment by PaulDalek** [comment]
Checked it, everything works as expected.
