### ISSUE TITLE
EPIPE issue on v2.0.0

### ISSUE THREAD

**Issue by petahz** [highcharts/node-export-server#80]
Using Docker
system : ubuntu 14 04
node : v6.11.0
npm: 5.1.0
node-export-server: 2.0.0

Using the example straight from the README to use as a node-module. Getting the following error:

> error:
> uncaughtException: write EPIPE
> { date: 'Tue Sep 12 2017 21:31:44 GMT+0000 (UTC)',
>    process:
>     { pid: 203,
>       uid: 0,
>       gid: 0,
>       cwd: '/sites/charts',
>       execPath: '/usr/src/node/bin/node',
>       version: 'v6.11.0',
>       argv:
>        [ '/usr/src/node/bin/node',
>          '/sites/charts/bin/www',
>          '--debug=3001' ],
>       memoryUsage:
>        { rss: 56995840,
>          heapTotal: 31543296,
>          heapUsed: 23275608,
>          external: 216372 } },
>    os: { loadavg: [ 0, 0, 0 ], uptime: 276783 },
>    trace:
>     [ { column: 11,
>         file: 'util.js',
>         function: 'exports._errnoException',
>         line: 1018,
>         method: '_errnoException',
>         native: false },
>       { column: 14,
>         file: 'net.js',
>         function: 'WriteWrap.afterWrite',
>         line: 800,
>         method: 'afterWrite',
>         native: false } ],
>   stack:
>     [ 'Error: write EPIPE',
>      '    at exports._errnoException (util.js:1018:11)',
>       '    at WriteWrap.afterWrite (net.js:800:14)' ] }
>  uncaughtException: { Error: write EPIPE
>      at exports._errnoException (util.js:1018:11)
>      at WriteWrap.afterWrite (net.js:800:14) code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }
>

**Comment by petahz** [comment]
Seems to just be a Docker issue with PhantomJS. Need to make sure the correct binary is installed.
