### ISSUE TITLE
error run server

### ISSUE THREAD

**Issue by manvfx** [highcharts/node-export-server#86]
C:\Users\MAN\Desktop\node-export-server\bin>highcharts-export-server --enableServer 1
    __  ___       __         __               __
   / / / (_)___ _/ /_  _____/ /_  ____ ______/ /______
  / /_/ / / __ `/ __ \/ ___/ __ \/ __ `/ ___/ __/ ___/
 / __  / / /_/ / / / / /__/ / / / /_/ / /  / /_(__  )
/_/ /_/_/\__, /_/ /_/\___/_/ /_/\__,_/_/   \__/____/
        ____//___/                  __     _____
       / ____/  ______  ____  _____/ /_   / ___/___  ______   _____  _____
      / __/ | |/_/ __ \/ __ \/ ___/ __/   \__ \/ _ \/ ___/ | / / _ \/ ___/
     / /____>  </ /_/ / /_/ / /  / /_    ___/ /  __/ /   | |/ /  __/ /
    /_____/_/|_/ .___/\____/_/   \__/   /____/\___/_/    |___/\___/_/
              /_/

Wed Oct 04 2017 16:26:56 GMT+0330 (Iran Standard Time) [error] socket error: { Error: listen EADDRINUSE :::7801
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1406:7)
    at Object.start [as startServer] (C:\Users\MAN\Desktop\node-export-server\lib\server.js:330:24)
    at Object.<anonymous> (C:\Users\MAN\Desktop\node-export-server\bin\cli.js:180:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 7801 }

**Comment by cvasseng** [comment]
You already have another service listening to port 7801. Try running it on a different port (`--port <number>`, and make sure the export server isn't already running.

**Comment by cvasseng** [comment]
If you're still having issues with this, please feel free to re-open this issue, or post a new one.
