### ISSUE TITLE
Server Test error on windows 10

### ISSUE THREAD

**Issue by arisliang** [highcharts/node-export-server#87]
I just installed the export server from npm, and tried the Server Test on a windows 10 machine, the code is:

server:
`highcharts-export-server --enableServer 1`

curl client:
`curl -H "Content-Type: application/json" -X POST -d '{"infile":{"title": {"text": "Steep Chart"}, "xAxis": {"categories": ["Jan", "Feb", "Mar"]}, "series": [{"data": [29.9, 71.5, 106.4]}]}}' 127.0.0.1:7801 -o mychart.png`

curl generates error as below:
**********
curl: (3) [globbing] unmatched brace in column 1
curl: (3) [globbing] unmatched close brace/bracket in column 12
curl: (6) Could not resolve host: xAxis
curl: (3) [globbing] unmatched brace in column 1
curl: (3) [globbing] bad range in column 2
curl: (6) Could not resolve host: Feb,
curl: (3) [globbing] unmatched close brace/bracket in column 4
curl: (6) Could not resolve host: series
curl: (3) [globbing] bad range specification in column 2
curl: (3) [globbing] bad range in column 2
curl: (6) Could not resolve host: 71.5,
curl: (3) [globbing] unmatched close brace/bracket in column 6
SyntaxError: Unexpected token &#39;<br> &nbsp; &nbsp;at parse (C:\Users\user\AppData\Roaming\npm\node_modules\highcharts-export-server\node_modules\body-parser\lib\types\json.js:83:15)<br> &nbsp; &nbsp;at C:\Users\user\AppData\Roaming\npm\node_modules\highcharts-export-server\node_modules\body-parser\lib\read.js:116:18<br> &nbsp; &nbsp;at invokeCallback (C:\Users\user\AppData\Roaming\npm\node_modules\highcharts-export-server\node_modules\raw-body\index.js:262:16)<br> &nbsp; &nbsp;at done (C:\Users\user\AppData\Roaming\npm\node_modules\highcharts-export-server\node_modules\raw-body\index.js:251:7)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (C:\Users\user\AppData\Roaming\npm\node_modules\highcharts-export-server\node_modules\raw-body\index.js:307:7)<br> &nbsp; &nbsp;at emitNone (events.js:86:13)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:185:7)<br> &nbsp; &nbsp;at endReadableNT (_stream_readable.js:974:12)<br> &nbsp; &nbsp;at _combinedTickCallback (internal/process/next_tick.js:80:11)<br> &nbsp; &nbsp;at process._tickCallback (internal/process/next_tick.js:104:9)
**********

server side error:
*************
SyntaxError: Unexpected token '
    at parse (C:\Users\user\AppData\Roaming\npm\node_modules\highcharts-export-server\node_modules\body-parser\lib\types\json.js:83:15)
    at C:\Users\user\AppData\Roaming\npm\node_modules\highcharts-export-server\node_modules\body-parser\lib\read.js:116:18
    at invokeCallback (C:\Users\user\AppData\Roaming\npm\node_modules\highcharts-export-server\node_modules\raw-body\index.js:262:16)
    at done (C:\Users\user\AppData\Roaming\npm\node_modules\highcharts-export-server\node_modules\raw-body\index.js:251:7)
    at IncomingMessage.onEnd (C:\Users\user\AppData\Roaming\npm\node_modules\highcharts-export-server\node_modules\raw-body\index.js:307:7)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
***********

Strangely, same code works in a bash shell.

curl version is 7.56.0

**Comment by arisliang** [comment]
This seems to be a curl related issue. The code works with Postman on same machine.
