### ISSUE TITLE
Can not run example code with the exception

### ISSUE THREAD

**Issue by lonelywolf4git** [highcharts/node-export-server#96]
I use the following example code and get the exception:

const exporter = require('highcharts-export-server')

// Export settings 
var exportSettings = {
  type: 'png',
  options: {
    title: {
      text: 'My Chart'
    },
    xAxis: {
      categories: ['Jan', 'Feb', 'Mar', 'Apr', 'Mar', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
    },
    series: [
      {
        type: 'line',
        data: [1, 3, 2, 4]
      },
      {
        type: 'line',
        data: [5, 3, 4, 2]
      }
    ]
  }
}

// Set up a pool of PhantomJS workers
exporter.initPool()

// Perform an export
/*
    Export settings corresponds to the available CLI arguments described
    above.
*/
exporter.export(exportSettings, function (err, res) {
  // The export result is now in res.
  // If the output is not PDF or SVG, it will be base64 encoded (res.data).
  // If the output is a PDF or SVG, it will contain a filename (res.filename).

  // Kill the pool when we're done with it, and exit the application
  exporter.killPool()
  process.exit(1)
})
The exception:
uncaughtException: TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:289:26)
    at exports.spawn (child_process.js:380:9)
    at Object.exports.exec (/Users/user/ProjectSrcCode/json-to-chart/node_modules/phantomjs-prebuilt/lib/phantomjs.js:72:10)
    at spawnWorker (/Users/user/ProjectSrcCode/json-to-chart/node_modules/highcharts-export-server/lib/phantompool.js:127:32)
    at Object.init [as initPool] (/Users/user/ProjectSrcCode/json-to-chart/node_modules/highcharts-export-server/lib/phantompool.js:329:9)
    at Object.<anonymous> (/Users/user/ProjectSrcCode/json-to-chart/bin/json_to_converter.js:27:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

**Comment by cvasseng** [comment]
Which version of node.js and npm are you using?

**Comment by tlhe** [comment]
i can run ,bug get 
![image](https://user-images.githubusercontent.com/32058135/35262683-96fe6c78-0050-11e8-8f00-cb3bc340415c.png)

**Comment by shaima029** [comment]
@lonelywolf4git 

Did you figure out how to get over it?

**Comment by cvasseng** [comment]
@tlhe The error you're having is not related to the OP. If you get an image back saying that the export server is not configured, something has gone wrong when installing the server. If you have cloned the repo and are running it manually, make sure that you've run `npm install` and that it doesn't fail. If you're behind a proxy, you need to configure it as explained [here](https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables).

@shaima029 / @lonelywolf4git Can you supply more information, specifically which version of the export server you're using, and the node version you're on? We are not able to reproduce this.

**Comment by psegura87** [comment]
I keep getting the same error, yet can't figure out the problem.  Everything seems to install correctly

I am using automatic deployment of highcharts export server on Heroku. I followed all the documentation, including setting env variables:

ACCEPT_HIGHCHARTS_LICENSE=YES

HIGHCHARTS_USE_STYLED=NO

HIGHCHARTS_VERSION=latest

As well as tried configuring my package.json:

"scripts": {

"preinstall": "export ACCEPT_HIGHCHARTS_LICENSE=1"
},

But I still keep receiving the same error when building png files.

"Export Server not configured. If you installed by running npm install -g highcharts-export-server and declined the license agreement, you need to reinstall to confirm."

I've cleared the cached from heroku, even reinstalled the package from heroku application console and accepted the agreement that way. Still no help. Any thoughts?

**Comment by psegura87** [comment]
I resolved the issue.  For Heroku, I shouldn;t set the env variables inside node.js or inside the .env.  I should set ACCEPT_HIGHCHARTS_LICENSE=YES inside the herokus setting panel - config_vars

**Comment by abtx** [comment]
@psegura87 I've run `node node_modules/highcharts-export-server/build.js` on the server, as well as set `ACCEPT_HIGHCHARTS_LICENSE=YES ` in Heroku, but still getting `Export Server not configured!`. `highcharts-export-server` is installed as a dependency and works locally, but not in heroku. I've not set up the proxy as suggested by @cvasseng, did you do it?

**Comment by arunkumarFMQ** [comment]
> 
> 
> Have also been seeing this behavior.
> 
> After adding the module, importing, and running the example.
> I am getting the same error message as @tlhe, this output when creating an image.
> ![image](https://user-images.githubusercontent.com/3508358/44691564-126cfb00-aa14-11e8-8a61-fb5c432e701d.png)
> 
> One thing to note, building the module specifically by running `node node_modules/highcharts-export-server/build.js` fixed the issue for me. The library began exporting successfully afterwards.
> 
> This seems like it shouldn't be a necessary step but if it is, let me know, and I can update the documentation.
> 
> I tried just adding the env variable like @psegura87 mentioned to the .env file, but that wasn't functioning for me. At least not locally, I'm not using Heroku.

After running command node node_modules/highcharts-export-server/build.js fixed the issue for me as well. Thanks

**Comment by nchalco** [comment]
I am also experiencing the above error while trying to run my own server, I've read through the install docs multiple times and have also tried both the suggestions above by setting the env variable `ACCEPT_HIGHCHARTS_LICENSE: "1"` and running `node node_modules/highcharts-export-server/build.js`
I am trying to deploy this service using Google cloud. 
Node v10.14.2
highcharts-export-server v2.0.24

<img width="450" alt="Screen Shot 2019-05-30 at 2 17 11 PM" src="https://user-images.githubusercontent.com/8839067/58660961-a9911700-82f4-11e9-855a-123e6a34e7ab.png">

**Comment by krishnasai101** [comment]
![image](https://user-images.githubusercontent.com/48314123/62359465-778a7400-b534-11e9-83c9-a65c552ba5f0.png)


The same issue with me too, I went through build.js file. There was lke this


` agree: {
            description: 'Agree to the license terms? y/n',
            required: true,
            default: 'no',
            message: 'Please enter (y)es or (n)o',
            conform: boolConform
        },`


Why can't it be like this? Will there be any error as whoever installs need to accept the license.

  agree: {
      description: 'Agree to the license terms? y/n',
      required: true,
      default: process.env.ACCEPT_HIGHCHARTS_LICENSE || 'y',
      message: 'Please enter (y)es or (n)o',
      conform: boolConform
    },


Can check this please??

**Comment by krishnasai101** [comment]
> > Have also been seeing this behavior.
> > After adding the module, importing, and running the example.
> > I am getting the same error message as @tlhe, this output when creating an image.
> > ![image](https://user-images.githubusercontent.com/3508358/44691564-126cfb00-aa14-11e8-8a61-fb5c432e701d.png)
> > One thing to note, building the module specifically by running `node node_modules/highcharts-export-server/build.js` fixed the issue for me. The library began exporting successfully afterwards.
> > This seems like it shouldn't be a necessary step but if it is, let me know, and I can update the documentation.
> > I tried just adding the env variable like @psegura87 mentioned to the .env file, but that wasn't functioning for me. At least not locally, I'm not using Heroku.
> 
> First run npm install -g highcharts-export-server & then running command node node_modules/highcharts-export-server/build.js fixed the issue for me on windows. Thanks

This did not work for me man. could you help in other ways of doing it?

**Comment by bejoinka** [comment]
Running Heroku web workers, nodeJS, where highcharts-export-server is a small part of my app.

I can confirm that ACCEPT_HIGHCHARTS_LICENSE=YES in heroku config BEFORE deploying the app works just fine.

A couple of things to think about if you are still having problems:
1) Run a debug and check the env settings (and Highchart settings) when you try posting work to one of the workers (phantompool.postWork)
2) set your log level to 4 in the config when you start (something like Highcharts.initPool({logLevel: 4})

Good luck!

**Comment by SLSJL** [comment]
In my case, I configure out that this issue cause by wrong input at the step to confirm the CND.

At CDN step, just press ENTER instead of input 'Y'. Then all the dependencies will pull from the CDN.

Run the node program, image will be generated correctly.

![Screen Cap](https://user-images.githubusercontent.com/16145313/119532768-c499a300-bdb7-11eb-8aa9-09184c1de0c0.png)

Configure the package by running command line as follows at nodejs project root, as mention above
```
 node node_modules/highcharts-export-server/build.js
```

**Comment by PaulDalek** [comment]
Closing issue due to inactivity.
